### ISSUE TITLE
ModuleNotFoundError: No module named 'lib.helper'

### ISSUE THREAD

**Issue by myugan** [menkrep1337/XSSCon#3]
This error appear when i use
```
$ python3 xsscon.py
Traceback (most recent call last):
  File "xsscon.py", line 7, in <module>
    from lib.helper.helper import *
ImportError: No module named lib.helper.helper
```
I tried to install helper module using `pip3 install helper` but still error, can you create file module like `requirement.txt`

**Comment by menkrep1337** [comment]
You must have python with version 3.5 and above
check with
python3 --version

**Comment by lacroutelacroute** [comment]
use 
python3  --version
Python 3.7.3rc1

execution cause crash
$ python3 ./xsscon.py 
Traceback (most recent call last):
  File "./xsscon.py", line 7, in <module>
    from lib.helper.helper import *
  File "/opt/XSSCon/XSSCon/lib/helper/helper.py", line 37
    =======
     ^
SyntaxError: invalid syntax

**Comment by menkrep1337** [comment]
Fixed

**Comment by robertoraimondo** [comment]
# cd /opt/
/opt# git clone https://github.com/menkrep1337/XSSCon.git
/opt# cd XSSCon/
/opt/XSSCon# pip3 install -r requirements.txt
/opt/XSSCon# pip install https://github.com/dianakhuang/pytumblr/archive/diana/python-3-support.zip
/opt/XSSCon# pip3 install helpers
/opt/XSSCon# nano /opt/XSSCon/helper.py

# -*- coding: utf-8 -*-

/opt/XSSCon# pip3 install pytumblr
/opt/XSSCon# nano xsscon.py

import pytumblr.helpers

/opt/XSSCon# python3 xsscon.py

__  ______ ____   ____
\ \/ / ___/ ___| / ___|___  _ __
 \  /\___ \___ \| |   / _ \| '_ \ {v0.5 Final}
 /  \ ___) |__) | |__| (_) | | | | https://github.com/menkrep1337/XSSCon
/_/\_\____/____/ \____\___/|_| |_|
<<<<<<< HEAD

[14:23:00] [INFO] Starting XSSCon...
usage: XSSCon -u <target> [options]

Options:
  --help            Show usage and help parameters
  -u                Target url (e.g. http://testphp.vulnweb.com)
  --depth           Depth web page to crawl. Default: 2
  --payload-level   Level for payload Generator, 7 for custom payload. {1...6}. Default: 6
  --payload         Load custom payload directly (e.g. <script>alert(2005)</script>)
  --method          Method setting(s): 
                    	0: GET
                    	1: POST
                    	2: GET and POST (default)
  --user-agent      Request user agent (e.g. Chrome/2.1.1/...)
  --single          Single scan. No crawling just one address
  --proxy           Set proxy (e.g. {'https':'https://10.10.1.10:1080'})
  --about           Print information about XSSCon tool
  --cookie          Set cookie (e.g {'ID':'1094200543'})

Github: https://www.github.com/menkrep1337/XSSCon
Version: 0.5 Final
